### ISSUE TITLE
The RMRK webpage crashes when entering an (insanely) large price for sale

### ISSUE THREAD

**Issue by dineshpinto** [Swader/rmrk-web#4]
# Steps to Reproduce

+ List an NFT for sale with the "List for Sale" button.
+ Enter a large price, I could get up to 21 9s (ie. 999999999999999999999)
+ The webpage crashes with a "went-wrong" error message

# Solution
Perhaps a more graceful way of limiting the maximum input to the listing price text box.

**Comment by brave-i** [comment]
Hi, I'm full stack and block chain developer  and looking for new position. Can you please help me?

**Comment by Yuripetusko** [comment]
> Hi, I'm full stack and block chain developer  and looking for new position. Can you please help me?

Please use an email in job description to apply
