### ISSUE TITLE
WebXR for 3D models

### ISSUE THREAD

**Issue by playing-with-dust** [Swader/rmrk-web#6]
Sorry for the feature request, but I've been using WebXR for another project and the integration was extremely simple - I wondered if it would be a nice idea to integrate it to the 3D viewer, as it support most headsets including e.g. google cardboard on mobile: https://immersive-web.github.io/webxr-samples/

**Comment by playing-with-dust** [comment]
(obviously regarding the singular website, but maybe someone will see this!)

**Comment by onerawartist** [comment]
@playing-with-dust 


i came to ask for the same thing, maybe 
i saw that kodadot has the feature to use AR when you mint a GLTF nft , and i wonder why singular doesn't have that 
check the video in the tweet 
https://twitter.com/one_raw_artist/status/1463243070237982723?s=20

**Comment by Swader** [comment]
rmrk.upvoty.com for features please
